name: C++ CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    # ---------------------------------------------
    # Two-dimensional matrix: OS × build-type
    # ---------------------------------------------
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Release]          # add "Debug" later if you like

    name: ${{ matrix.os }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    steps:
    # -------------- checkout ----------------------
    - name: Checkout
      uses: actions/checkout@v4

    # -------------- dependencies ------------------
    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev libssl-dev ninja-build

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # -------------- configure ---------------------
    - name: Configure CMake
      run: |
        cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      shell: bash

    # -------------- build -------------------------
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
      shell: bash

    # -------------- tests -------------------------
    - name: Run unit tests
      run: ctest -C ${{ matrix.build_type }} --test-dir build --output-on-failure
      shell: bash
