name: C++ CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build_type: [Release]         # add Debug if you wish

    name: ${{ matrix.os }} / ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}

    env:
      SOURCE_DIR: BlokchainSim/BlokchainSim   # <── your CMakeLists.txt lives here

    # ----------------------------------------------------------
    # 0) Checkout repository
    # ----------------------------------------------------------
    steps:
    - uses: actions/checkout@v4

    # ----------------------------------------------------------
    # 1) Dependencies
    # ----------------------------------------------------------
    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libssl-dev qt6-base-dev

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Qt 6 on Windows via aqt
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        pip install aqtinstall
        aqt install-qt windows desktop 6.6.2 win64_msvc2019_64 -m qtbase
        echo "QT_ROOT=$PWD/Qt/6.6.2/msvc2019_64" | Out-File -FilePath $env:GITHUB_ENV -Append

    # ----------------------------------------------------------
    # 2) Configure (points at nested SOURCE_DIR)
    # ----------------------------------------------------------
    - name: Configure CMake
      run: |
        cmake -S "$SOURCE_DIR" -B build -G Ninja \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_PREFIX_PATH="$QT_ROOT"
      shell: bash

    # ----------------------------------------------------------
    # 3) Build
    # ----------------------------------------------------------
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}
      shell: bash

    # ----------------------------------------------------------
    # 4) Unit tests
    # ----------------------------------------------------------
    - name: Run unit tests
      run: ctest -C ${{ matrix.build_type }} --test-dir build --output-on-failure
      shell: bash
